<?xml version="1.0" encoding="UTF-8"?>
<definitions
	name="clkio"
	xmlns:tns="http://ws.clkio.com"
	xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
	
	<types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://ws.clkio.com/user" schemaLocation="http://ws.clkio.com/schema/user.xsd"/>
			<xsd:import namespace="http://ws.clkio.com/email" schemaLocation="http://ws.clkio.com/schema/email.xsd"/>
			<xsd:import namespace="http://ws.clkio.com/profile" schemaLocation="http://ws.clkio.com/schema/profile.xsd"/>
		</xsd:schema>
	</types>
	<portType name="UserService">
        <operation name="hello">
            <input message="tns:Hello_hello"/>
            <output message="tns:Hello_helloResponse"/>
        </operation>
    </portType>
	<service name="ClkIOWs">
		<port name="UserService" binding="UserService">
			<soap:address location="REPLACE_WITH_ACTUAL_URL" />
		</port>
	</service>
</definitions>
