
package com.clkio.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.clkio.ws.domain.user.User;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LoginPort", targetNamespace = "http://ws.clkio.com")
@XmlSeeAlso({
    com.clkio.ws.ObjectFactory.class,
    com.clkio.ws.domain.common.ObjectFactory.class,
    com.clkio.ws.domain.email.ObjectFactory.class,
    com.clkio.ws.domain.login.ObjectFactory.class,
    com.clkio.ws.domain.user.ObjectFactory.class
})
public interface LoginPort {


    /**
     * 
     * @param user
     * @return
     *     returns java.lang.String
     * @throws ResponseException
     */
    @WebMethod
    @WebResult(name = "code", targetNamespace = "http://schemas.clkio.com/login")
    @RequestWrapper(localName = "doLogin", targetNamespace = "http://ws.clkio.com", className = "com.clkio.ws.domain.login.DoLogin")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://ws.clkio.com", className = "com.clkio.ws.domain.login.LoginResponse")
    public String doLogin(
        @WebParam(name = "user", targetNamespace = "http://schemas.clkio.com/login")
        User user)
        throws ResponseException
    ;

}
