
package com.clkio.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.clkio.ws.domain.common.Response;
import com.clkio.ws.domain.resetpassword.ConfirmResetPasswordRequest;
import com.clkio.ws.domain.resetpassword.ConfirmResetPasswordResponse;
import com.clkio.ws.domain.resetpassword.RequestResetPasswordRequest;
import com.clkio.ws.domain.resetpassword.ResetPasswordRequest;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ResetPasswordPort", targetNamespace = "http://ws.clkio.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.clkio.ws.domain.ObjectFactory.class,
    com.clkio.ws.domain.adjusting.ObjectFactory.class,
    com.clkio.ws.domain.clockinclockout.ObjectFactory.class,
    com.clkio.ws.domain.common.ObjectFactory.class,
    com.clkio.ws.domain.day.ObjectFactory.class,
    com.clkio.ws.domain.email.ObjectFactory.class,
    com.clkio.ws.domain.login.ObjectFactory.class,
    com.clkio.ws.domain.manualentering.ObjectFactory.class,
    com.clkio.ws.domain.profile.ObjectFactory.class,
    com.clkio.ws.domain.reason.ObjectFactory.class,
    com.clkio.ws.domain.resetpassword.ObjectFactory.class,
    com.clkio.ws.domain.timecard.ObjectFactory.class,
    com.clkio.ws.domain.user.ObjectFactory.class
})
public interface ResetPasswordPort {


    /**
     * 
     * @param request
     * @return
     *     returns com.clkio.ws.domain.common.Response
     * @throws ResponseException
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "http://schemas.clkio.com", partName = "result")
    public Response requestResetPassword(
        @WebParam(name = "requestResetPasswordRequest", targetNamespace = "http://schemas.clkio.com", partName = "request")
        RequestResetPasswordRequest request)
        throws ResponseException
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.clkio.ws.domain.resetpassword.ConfirmResetPasswordResponse
     * @throws ResponseException
     */
    @WebMethod
    @WebResult(name = "confirmResetPasswordResponse", targetNamespace = "http://schemas.clkio.com", partName = "result")
    public ConfirmResetPasswordResponse confirmResetPassword(
        @WebParam(name = "confirmResetPasswordRequest", targetNamespace = "http://schemas.clkio.com", partName = "request")
        ConfirmResetPasswordRequest request)
        throws ResponseException
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.clkio.ws.domain.common.Response
     * @throws ResponseException
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "http://schemas.clkio.com", partName = "result")
    public Response resetPassword(
        @WebParam(name = "resetPasswordRequest", targetNamespace = "http://schemas.clkio.com", partName = "request")
        ResetPasswordRequest request)
        throws ResponseException
    ;

}
