
package com.clkio.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "responseException", targetNamespace = "http://ws.clkio.com")
public class ResponseException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private com.clkio.ws.domain.common.ResponseException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ResponseException(String message, com.clkio.ws.domain.common.ResponseException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ResponseException(String message, com.clkio.ws.domain.common.ResponseException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.clkio.ws.domain.common.ResponseException
     */
    public com.clkio.ws.domain.common.ResponseException getFaultInfo() {
        return faultInfo;
    }

}
